Preconditions
wolox-training/jbe-java pull request #9
Opened 2020-10-14 21:37 UTC by juandbc

## Summary
* Add guava dependency
* Add checkNotNull precondition to model classes setters

## Trello Card
https://trello.com/c/xqOXL9pq/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters

2020-10-14 21:48 UTC, jeymarsonwolox requested changes
Great Job!! Validate nulls and blanks in strings

2020-10-14 21:48 UTC, jeymarsonwolox commented on src/main/java/wolox/training/models/Book.java
> +        this.author = checkNotNull(author);
check blank string

2020-10-14 21:48 UTC, jeymarsonwolox commented on src/main/java/wolox/training/models/Book.java
> +        this.image = checkNotNull(image);
same

2020-10-15 00:03 UTC, jeymarsonwolox approved these changes, later dismissed

2020-10-15 13:32 UTC, Gianni-Nicolas requested changes
Great Job 👍

2020-10-15 13:32 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/User.java
> +        this.birthdate = checkNotNull(birthdate);
After checking if it is null, you can check if the date is after the current one (the date of birth must always be earlier).

2020-10-15 13:32 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/Book.java
>          this.year = year;
After checking if it is null or empty, you can check if the content of the year field is a number.

You can use the StringUtils.isNumeric method. [import org.apache.commons.lang3.StringUtils;]

2020-10-15 13:32 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/Book.java
> +        checkArgument(!Strings.isNullOrEmpty(isbn));
After checking if it is null or empty, you can check if the content of the isbn field is a number.

2020-10-15 13:32 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/Book.java
>          this.pages = pages;
After checking if it is null or empty, you can check if the content of the page field is greater than 0.

2020-10-15 14:27 UTC, jeymarsonwolox submitted a review, later dismissed

2020-10-15 19:11 UTC, Gianni-Nicolas approved these changes

2020-10-15 20:12 UTC, jeymarsonwolox approved these changes

2020-10-15 20:12 UTC, merged